### ISSUE TITLE
ValueError: batch_size should be a positive integer value, but got batch_size=0

### ISSUE THREAD

**Issue by Tato14** [vqdang/hover_net#175]
Hi, 
I am trying to run the training on consep dataset. I run `extract_patches.py` without issue but when I try to run `runtrain.py` I got the following error:

```
(hovernet) [jgibert@oslo hover_net]$ python run_train.py --gpu=0
Detect #GPUS: 0
Using manual seed: 10
Dataset train: 1728
Traceback (most recent call last):
  File "run_train.py", line 305, in <module>
    trainer.run()
  File "run_train.py", line 289, in run
    phase_info, engine_opt, save_path, prev_log_dir=prev_save_path
  File "run_train.py", line 161, in run_once
    fold_idx=fold_idx,
  File "run_train.py", line 130, in _get_datagen
    worker_init_fn=worker_init_fn,
  File "/home/jgibert/anaconda3/envs/hovernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 230, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/home/jgibert/anaconda3/envs/hovernet/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 198, in __init__
    "but got batch_size={}".format(batch_size))
ValueError: batch_size should be a positive integer value, but got batch_size=0
```
The `config.py` file:
```
(hovernet) [jgibert@oslo hover_net]$ cat config.py 
import importlib
import random

import cv2
import numpy as np

from dataset import get_dataset


class Config(object):
    """Configuration file."""

    def __init__(self):
        self.seed = 10

        self.logging = True

        # turn on debug flag to trace some parallel processing problems more easily
        self.debug = False

        model_name = "hovernet"
        model_mode = "original" # choose either `original` or `fast`

        if model_mode not in ["original", "fast"]:
            raise Exception("Must use either `original` or `fast` as model mode")

        nr_type = 5 # number of nuclear types (including background)

        # whether to predict the nuclear type, availability depending on dataset!
        self.type_classification = True

        # shape information - 
        # below config is for original mode. 
        # If original model mode is used, use [270,270] and [80,80] for act_shape and out_shape respectively
        # If fast model mode is used, use [256,256] and [164,164] for act_shape and out_shape respectively
        aug_shape = [540, 540] # patch shape used during augmentation (larger patch may have less border artefacts)
        act_shape = [270, 270] # patch shape used as input to network - central crop performed after augmentation
        out_shape = [80, 80] # patch shape at output of network

        if model_mode == "original":
            if act_shape != [270,270] or out_shape != [80,80]:
                raise Exception("If using `original` mode, input shape must be [270,270] and output shape must be [80,80]")
        if model_mode == "fast":
            if act_shape != [256,256] or out_shape != [164,164]:
                raise Exception("If using `original` mode, input shape must be [256,256] and output shape must be [164,164]")

        self.dataset_name = "consep" # extracts dataset info from dataset.py
        self.log_dir = "logs/" # where checkpoints will be saved

        # paths to training and validation patches
        self.train_dir_list = [
            "/mnt/isilon/Breast_HMAR/HoverNet/consep/consep/train/270x270_128x128"
        ]
        self.valid_dir_list = [
            "/mnt/isilon/Breast_HMAR/HoverNet/consep/consep/valid/270x270_128x128"
        ]

        self.shape_info = {
            "train": {"input_shape": act_shape, "mask_shape": out_shape,},
            "valid": {"input_shape": act_shape, "mask_shape": out_shape,},
        }

        # * parsing config to the running state and set up associated variables
        self.dataset = get_dataset(self.dataset_name)

        module = importlib.import_module(
            "models.%s.opt" % model_name
        )
        self.model_config = module.get_config(nr_type, model_mode)
```

Any hints why I got this error? Thanks!

**Comment by Taslim-M** [comment]
I think this is because you do not have a GPU. (detected 0). The batch_size is being calculated by multiplying the batch_size*nr_gpus, so if you do not have a GPU this variable is set to 0.

**Comment by Taslim-M** [comment]
@Tato14 if you check torch.cuda.device_count() from your conda shell, does it give you a positive integer?

**Comment by Taslim-M** [comment]
@Tato14 if you do have a GPU then try running without the --gpu=0

**Comment by Tato14** [comment]
Hi, sorry for the late response. If I hardcode `batch_size`, the error dissapear. It seems that `--gpu=0` is not properly managed. If I changed to `--gpu=2`, `run_train.py` picks the correct GPU
