### ISSUE TITLE
AttributeError: 'FileLoader' object has no attribute 'shape_augs' Processing: |          | 0/1323[00:00<?,?it/s]Batch = nan|EMA = nan

### ISSUE THREAD

**Issue by homxxx** [vqdang/hover_net#180]
C:\Anaconda3.5.2\envs\torch_mai\python.exe E:/Hom_workspace/sell_seg/hover_net-master/run_train.py
Detect #GPUS: 1
Using manual seed: 10
Dataset train: 1323
Dataset valid: 686
----------------EPOCH 1
Processing: |          | 0/1323[00:00<?,?it/s]Batch = nan|EMA = nanTraceback (most recent call last):
  File "E:/Hom_workspace/sell_seg/hover_net-master/run_train.py", line 307, in <module>
    trainer.run()
  File "E:/Hom_workspace/sell_seg/hover_net-master/run_train.py", line 290, in run
    phase_info, engine_opt, save_path, prev_log_dir=prev_save_path
  File "E:/Hom_workspace/sell_seg/hover_net-master/run_train.py", line 266, in run_once
    main_runner.run(opt["nr_epochs"])
  File "E:\Hom_workspace\sell_seg\hover_net-master\run_utils\engine.py", line 172, in run
    for data_batch in self.dataloader:
  File "C:\Anaconda3.5.2\envs\torch_mai\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Anaconda3.5.2\envs\torch_mai\lib\site-packages\torch\utils\data\dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Anaconda3.5.2\envs\torch_mai\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Anaconda3.5.2\envs\torch_mai\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Hom_workspace\sell_seg\hover_net-master\dataloader\train_loader.py", line 85, in __getitem__
    if self.shape_augs is not None:
AttributeError: 'FileLoader' object has no attribute 'shape_augs'
Processing: |          | 0/1323[00:00<?,?it/s]Batch = nan|EMA = nan

**Comment by vqdang** [comment]
Stale issue with no idea what the user wants. Feel free to reopen if you stil have problems.
