### ISSUE TITLE
tp_map issue

### ISSUE THREAD

**Issue by LeoMira-1999** [vqdang/hover_net#207]
Hi,

I'm trying to run your model with my dataset. The data I have is laid out as such:

-- train/
-- images/
--- img0.tiff
--- img1.tiff
    ...
-- masks/
--- img0_mask0.tiff
--- img0_mask1.tiff
--- img1_mask0.tiff
--- img1_mask1.tiff
--- img1_mask2.tiff
    ...

This layout is used in a train and test (valid) folder. I successfully modified the dataset.py to have it set up nicely in .npy format as required.

However, when i run `python run_train.py --gpu='2'` i get this error:

```python
Detect #GPUS: 1
Using manual seed: 10
Dataset train: 3548
Dataset valid: 450
----------------EPOCH 1
Processing: |                                                                                                                  | 0/221[00:00<?,?it/s]Batch = nan|EMA = nandict_keys(['img', 'hv_map', 'np_map'])
Traceback (most recent call last):
  File "run_train.py", line 305, in <module>
    trainer.run()
  File "run_train.py", line 289, in run
    phase_info, engine_opt, save_path, prev_log_dir=prev_save_path
  File "run_train.py", line 265, in run_once
    main_runner.run(opt["nr_epochs"])
  File "/home/leonardo/Pipeline/hover_net/run_utils/engine.py", line 182, in run
    step_output = self.run_step(data_batch, step_run_info)
  File "/home/leonardo/Pipeline/hover_net/models/hovernet/run_desc.py", line 49, in train_step
    true_tp = batch_data["tp_map"]
KeyError: 'tp_map'
Processing: |                                                                                                                  | 0/221[00:00<?,?it/s]Batch = nan|EMA = nan` 
```

Any ideas on why i have this?

Best regards

Leonardo

**Comment by LeoMira-1999** [comment]
Indeed that was the problem, perfect it's working great ! thanks a lot !!
