### ISSUE TITLE
Train my own data

### ISSUE THREAD

**Issue by Acmenwangtuo** [vqdang/hover_net#22]
When i train my data,which is only two kind of nuclei,i find that:

![图片3](https://user-images.githubusercontent.com/25858179/74667804-ed0f1680-51de-11ea-9f0f-3c08b48ccddf.png)

how can i solve it

**Comment by Acmenwangtuo** [comment]
When i set  the nuclei_type = 3,it can not work,while,when the nucei_type_5,it can work

**Comment by simongraham** [comment]
Hi @Acmenwangtuo ,

You need to set `self.nr_types=3` at:

https://github.com/vqdang/hover_net/blob/master/src/config.py#L25 .

Of course, this also requires that your input data is correct. I would advise that you ensure that your input is in the same format that we use. Please keep us informed how you get on.

**Comment by Acmenwangtuo** [comment]
yeah i have set the nr_types = 3 and my input data is correct, i am sure that store patches in a 5 dimensional numpy array with channels [RGB, inst, type].

**Comment by vqdang** [comment]
Hi @Acmenwangtuo, please post a full-screen shot of the error messages, without that it would be very hard to track down the problem. Additionally, please details as much as possible what changes have been made.

At this moment, I can only think the error may arise from 
https://github.com/vqdang/hover_net/blob/38bf1e849f7ed04f6d14769837a9ca3f9cc66fe1/src/model/graph.py#L282-L290 where we hard-coded the number of nuclei types, so it may make a problem for you.

**Comment by Acmenwangtuo** [comment]
yeah，i also think the erro is arsie from the grapy.py&nbsp; the reason is beyond the boundary ,i will gave you the log later




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"vqdang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月18日(星期二) 晚上9:46
收件人:&nbsp;"vqdang/hover_net"<hover_net@noreply.github.com&gt;;
抄送:&nbsp;"歪比歪比"<1198653145@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [vqdang/hover_net] Train my own data (#22)




Hi @Acmenwangtuo, please post a full-screen shot of the error messages, without that it would be very hard to track down the problem. Additionally, please details as much as possible what changes have been made.
 
At this moment, I can only think the error may arise from
 https://github.com/vqdang/hover_net/blob/38bf1e849f7ed04f6d14769837a9ca3f9cc66fe1/src/model/graph.py#L282-L290 where we hard-coded the number of nuclei types, so it may make a problem for you.

**Comment by Acmenwangtuo** [comment]
> Hi @Acmenwangtuo, please post a full-screen shot of the error messages, without that it would be very hard to track down the problem. Additionally, please details as much as possible what changes have been made.
> 
> At this moment, I can only think the error may arise from
> https://github.com/vqdang/hover_net/blob/38bf1e849f7ed04f6d14769837a9ca3f9cc66fe1/src/model/graph.py#L282-L290
> 
> where we hard-coded the number of nuclei types, so it may make a problem for you.

this is my error log ,and i also think the error from the graph.py

**Comment by Acmenwangtuo** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 3 of dimension 3 out of bounds. for 'tower0/strided_slice_20' (op: 'StridedSlice') with input shapes: [?,80,80,3], [2], [2], [2] and with computed input tensors: input[1] = <0 3>, input[2] = <0 4>, input[3] = <1 1>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 270, in <module>
    trainer.run()
  File "train.py", line 238, in run
    self.run_once(opt, sess_init=init_weights, save_dir=log_dir)
  File "train.py", line 210, in run_once
    launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(nr_gpus))
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/interface.py", line 87, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/tower.py", line 204, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/trainers.py", line 106, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/training.py", line 161, in build
    grad_list = DataParallelBuilder.build_on_towers(self.towers, get_grad_fn, devices)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/training.py", line 119, in build_on_towers
    ret.append(func())
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/tower.py", line 232, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/tower.py", line 284, in __call__
    output = self._tower_fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/model_desc.py", line 246, in _build_graph_get_cost
    ret = self.build_graph(*inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/model_desc.py", line 162, in build_graph
    return self._build_graph(args)
  File "/output/hover_net/src/model/graph.py", line 286, in _build_graph
    + dice_loss(soft_class[...,4], one_type[...,4]) 
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 525, in _slice_helper
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 691, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 8522, in strided_slice
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: slice index 3 of dimension 3 out of bounds. for 'tower0/strided_slice_20' (op: 'StridedSlice') with input shapes: [?,80,80,3], [2], [2], [2] and with computed input tensors: input[1] = <0 3>, input[2] = <0 4>, input[3] = <1 1>.

**Comment by simongraham** [comment]
Yes it seems that you will need to comment lines 285 and 286 of graph.py and then it should work. We will adapt this soon so that it updates automatically with the number of nuclear types. Please let us know if this fixes your problem.

**Comment by Acmenwangtuo** [comment]
> Yes it seems that you will need to comment lines 285 and 286 of graph.py and then it should work. We will adapt this soon so that it updates automatically with the number of nuclear types. Please let us know if this fixes your problem.

Yeah，I have done with what you say, the code has worked,the problem has been solved,Thank you for your patience and i hope you can fix the problem. Thank you again!
