### ISSUE TITLE
help me,please,please,please

### ISSUE THREAD

**Issue by giao-cloude** [vqdang/hover_net#225]
Processing: |                                                        | 0/0[00:00<?,?it/s]Batch = nan|EMA = nan
Traceback (most recent call last):
  File "run_train.py", line 305, in <module>
    trainer.run()
  File "run_train.py", line 289, in run
    phase_info, engine_opt, save_path, prev_log_dir=prev_save_path
  File "run_train.py", line 265, in run_once
    main_runner.run(opt["nr_epochs"])
  File "/home/fzuir/kzx/hovernet/run_utils/engine.py", line 197, in run
    self.__trigger_events(Events.EPOCH_COMPLETED)
  File "/home/fzuir/kzx/hovernet/run_utils/engine.py", line 123, in __trigger_events
    callback.run(self.state, event)
  File "/home/fzuir/kzx/hovernet/run_utils/callbacks/base.py", line 229, in run
    raw_output = state.step_output["raw"]
TypeError: 'NoneType' object is not subscriptable

**Comment by vqdang** [comment]
https://github.com/vqdang/hover_net/issues/161

See if that helps.
