### ISSUE TITLE
SyntaxError: EOL while scanning string literal during run_train.py

### ISSUE THREAD

**Issue by jpw011** [vqdang/hover_net#234]
I was able to successfully extract both my 'train' and 'valid' patches for the CoNSeP data, but get this error when using the `run_train.py --view=<dset>` execution. 

The `.npy` files are in the `540x540_164x160\` file and the path is correctly going to that location. I know this, because it says `Error: no .npy file found`, if the path is incorrectly set. 

```
PS C:\Users\jpw011> python run_train.py --view='train'
Traceback (most recent call last):
  File "C:\Users\jpw011\run_train.py", line 36, in <module>
    from config import Config
  File "C:\Users\jpw011\config.py", line 52
    "dataset\training_data\consep\consep\train\540x540_164x164\"
                                                                ^
SyntaxError: EOL while scanning string literal
```

```
PS C:\Users\jpw011> python run_train.py --view='valid'
Traceback (most recent call last):
  File "C:\Users\jpw011\run_train.py", line 36, in <module>
    from config import Config
  File "C:\Users\jpw011\config.py", line 52
    "dataset\training_data\consep\consep\train\540x540_164x164\"
                                                                ^
SyntaxError: EOL while scanning string literal
```
How can I complete the path to no longer receive this EOL message?

**Comment by simongraham** [comment]
Looks like there is a problem with the formatting of the string to the data path
