### ISSUE TITLE
Hi, I am getting list index out of range error during training

### ISSUE THREAD

**Issue by Noirombre** [vqdang/hover_net#264]
Hi,
I am getting list index out of range error during training
![微信图片_20231010174430](https://github.com/vqdang/hover_net/assets/147497628/110b40ae-0e67-40ae-bcce-07a30c0d1d34)

**Comment by Noirombre** [comment]
----------------EPOCH 1
Processing: |                                                                                                                                | 0/49[00:00<?,?it/s]Batch = nan|EMA = nanTraceback (most recent call last):
  File "run_train.py", line 305, in <module>
    trainer.run()
  File "run_train.py", line 288, in run
    self.run_once(
  File "run_train.py", line 265, in run_once
    main_runner.run(opt["nr_epochs"])
  File "E:\hover\hover_net-master\run_utils\engine.py", line 172, in run
    for data_batch in self.dataloader:
  File "E:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "E:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "E:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "E:\Anaconda\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\Anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\hover\hover_net-master\dataloader\train_loader.py", line 98, in __getitem__
    type_map = (ann[..., 1]).copy()
IndexError: index 1 is out of bounds for axis 2 with size 1

**Comment by Dingruotong** [comment]
I also encountered this situation, may I ask you to solve it

**Comment by simongraham** [comment]
Looks like your data has not been prepared right. It is trying to grab the second channel for the type map, which apparently isn't there.
