### ISSUE TITLE
Experiencing GPU issues while training

### ISSUE THREAD

**Issue by yuyu19970716** [vqdang/hover_net#277]
Hello, I'm having this problem while training, what is the reason for this?

Detect #GPUS: 1
Using manual seed: 10
Dataset train: 2656
Dataset valid: 2523
----------------EPOCH 1
Processing: |                                                                       | 0/166[00:00<?,?it/s]Batch = nan|EMA = nan/home/ubuntu/miniconda3/envs/lxy/lib/python3.8/site-packages/skimage/_shared/utils.py:157: UserWarning: Only one label was provided to `remove_small_objects`. Did you mean to use a boolean array?
  return func(*args, **kwargs)
/home/ubuntu/miniconda3/envs/lxy/lib/python3.8/site-packages/skimage/_shared/utils.py:157: UserWarning: Only one label was provided to `remove_small_objects`. Did you mean to use a boolean array?
  return func(*args, **kwargs)
Traceback (most recent call last):
  File "run_train.py", line 305, in <module>
    trainer.run()
  File "run_train.py", line 288, in run
    self.run_once(
  File "run_train.py", line 265, in run_once
    main_runner.run(opt["nr_epochs"])
  File "/home/ubuntu/LXY/Hover-net/hover_net-master/run_utils/engine.py", line 182, in run
    step_output = self.run_step(data_batch, step_run_info)
  File "/home/ubuntu/LXY/Hover-net/hover_net-master/models/hovernet/run_desc.py", line 58, in train_step
    pred_dict = model(imgs)
  File "/home/ubuntu/miniconda3/envs/lxy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lxy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lxy/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/home/ubuntu/miniconda3/envs/lxy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lxy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/LXY/Hover-net/hover_net-master/models/hovernet/net_desc.py", line 103, in forward
    imgs = imgs / 255.0  # to 0-1 range to match XY
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by haoyuanli66** [comment]
Hi, yuyu, I also have this problem. I wonder how did you solve it?
