### ISSUE TITLE
valid data

### ISSUE THREAD

**Issue by zerodohero** [vqdang/hover_net#55]
hello, excuse me, I have another question to consult you
In the extract_patches. Py file, there is only the generation of train data set, and there is no valid data set. However, the following error occurred when I was running train.This error can be traced to the line
                self.valid_dir = ['../CoNSeP/ Valid /%s/' % data_code_dict[self.model_type]].
Is this file to be separated from the train by itself?

[270, 270] [80, 80]
[270, 270] [80, 80]
[0827 17:32:55 @logger.py:108] WRN Log directory /media/vqdang/logs//v1.0//np_hv/00/ exists! Use 'd' to delete it. 
[0827 17:32:55 @logger.py:111] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit. 
Select Action: k (keep) / d (delete) / q (quit):d
[0827 17:32:59 @logger.py:73] Argv: D:/docum/PycharmProjects/hover_net-master/src/train.py --gpu='0'
2020-08-27 17:32:59.918335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.25GiB
2020-08-27 17:32:59.918657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-08-27 17:34:18.305952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 17:34:18.306130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-08-27 17:34:18.306229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-08-27 17:34:18.309802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 2943 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "D:/docum/PycharmProjects/hover_net-master/src/train.py", line 273, in <module>
    trainer.run()
  File "D:/docum/PycharmProjects/hover_net-master/src/train.py", line 240, in run
    self.run_once(opt, sess_init=init_weights, save_dir=log_dir)
  File "D:/docum/PycharmProjects/hover_net-master/src/train.py", line 197, in run_once
    valid_datagen, infs, list(range(nr_gpus))))
  File "D:\sofe\anaconda\envs\test\lib\site-packages\tensorpack\callbacks\inference_runner.py", line 218, in __init__
    assert self._size > 0, "Input for DataParallelInferenceRunner must have a size!"
AssertionError: Input for DataParallelInferenceRunner must have a size!
Failed to load OpenCL runtime

This is my workspace, the path is right
![image](https://user-images.githubusercontent.com/38395598/91441834-78124d00-e8a3-11ea-8b00-154406f62708.png)

**Comment by zerodohero** [comment]
Can You answer my question?Thank you very much

**Comment by simongraham** [comment]
Hi @zerodohero 

We will always endeavour to answer your questions, but we can't always guarantee to do this on the same day, so please be patient.

You will need to run `extract_patches.py` separately for both training and validation sets. We don't explicitly provide a validation set, but this can be selected from your train set. 

It is clear from above that you are trying to read data from `self.valid_dir = ['../CoNSeP/ Valid /%s/' % data_code_dict[self.model_type]]`. From looking at your workspace, you have not extracted the patches for a validation set and you only have the train patches. `self.train_dir` and `self.valid_dir` must be the exact paths to the training and validation patches. If this path is not correct, then an error will be given.

**Comment by zerodohero** [comment]
Thank you very much，I extracted a couple of validation sets from the train file, and the scale doesn't matter, right?

**Comment by vqdang** [comment]
Hi, i dont understand what you mean by `scale` here. 
For the training, what matter is like simon said, you have to provide correct directory paths for `self.valid_dir` and `self.train_dir` which contains the patches for training. The later code doesn't know about the scale or any metadata, it can only processes the format as defined by `extract_patches.py` . If you need to align something (magnification level, stain norm the RGB etc.), do it before performing the `extract_patches.py` .

**Comment by zerodohero** [comment]
Sorry, I mean the ratio of the training set to the validation set, because both are extracted from the train folder, and there is no obvious  ratio factor in the program.

**Comment by vqdang** [comment]
Hi, please refer to this https://github.com/vqdang/hover_net/issues/28#issuecomment-597698182

**Comment by zerodohero** [comment]
OK，Thank you very much，I will try .

**Comment by zerodohero** [comment]
Sorry to bother you again. I wonder whether train and valid can be the same?Or could valid be part of the train?I want to reproduce the result of the paper, but I haven't got a good result. What I am trying to do now is to copy 100 pieces from each block generated by each picture in the train to the valid.I use the Linux platform and the environment is the same
