### ISSUE TITLE
an AssertionError question

### ISSUE THREAD

**Issue by haiqinzhong** [vqdang/hover_net#57]
I'm sorry to bother you，I use your code and meet an AssertionError question :
Traceback (most recent call last):
  File "train.py", line 277, in <module>
    trainer.run()
  File "train.py", line 245, in run
    self.run_once(opt , sess_init=init_weights, save_dir=log_dir)
  File "train.py", line 179, in run_once
    train_datagen = self.get_datagen(opt['train_batch_size'], mode='train')
  File "train.py", line 167, in get_datagen
    nr_procs=nr_procs)
  File "/home/hqzhong/Programs/hover/src/loader/loader.py", line 72, in train_generator
    ds = BatchDataByShape(ds, batch_size, idx=0)
  File "/home/hqzhong/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 179, in __init__
    super(BatchDataByShape, self).__init__(ds, batch_size, remainder=False)
  File "/home/hqzhong/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 95, in __init__
    assert batch_size <= len(ds)
AssertionError
where I haven't read any data?
![1](https://user-images.githubusercontent.com/56585970/91955235-75957480-ed35-11ea-9369-9af47af49374.png)
the path should be fine?
img_ext = '.png'
    img_dir = 'data/CoNSeP/train/Images/'
    ann_dir = 'data/CoNSeP/train/Labels/'
    ####
    out_dir = "CoNSeP/train/%dx%d_%dx%d" % \
                        (win_size[0], win_size[1], step_size[0], step_size[1])

    # list of directories containing validation patches. 
        # For both train and valid directories, a comma separated list of directories can be used
        self.train_dir = ['CoNSeP/train/%s/' % data_code_dict[self.model_type]]
        self.valid_dir = ['CoNSeP/valid/%s/' % data_code_dict[self.model_type]]

**Comment by simongraham** [comment]
Hi @haiqinzhong ,

This error will be thrown when the data can't be found in the given location. It appears that you have not got your validation patches in the correct place.

**Comment by haiqinzhong** [comment]
Hi, @simongraham ,
Thanks for your reply.Yes, I'll try to modify it. But I'm a rookie in computer vision, can you tell me what's the “self.data_ext = '.npy' ” meaning , I search it in internet and find the ".npy" is a saved model file format , but you use the model file format is ".npz".

**Comment by haiqinzhong** [comment]
Hi,@simongraham 
whether I should use your dataset CoNSeP  into a .npy file. But if do it , doesn't influences the train?

**Comment by vqdang** [comment]
Hi, you need to run the `extract_patches.py` to generate the patches in .npy format, refer to #55 for latest detail, as well as how you should deal with validation data.

**Comment by haiqinzhong** [comment]
@vqdang  Thank you . I have find the same question in #12 ,Your answer made me understand more how to solove it . I'll try now. Wish I can run with your help.

**Comment by haiqinzhong** [comment]
I run the extract_patches.py and facing a error:
train_1.png
Traceback (most recent call last):
  File "extract_patches.py", line 59, in <module>
    ann_type = ann['class_map']
KeyError: 'class_map'
so I look at your CoNSep dataset I have down , and in readme.txt , you said the keys are: 'inst_map' 'type_map' 'inst_type' 'inst_centroid' . It haven't the class_map , whether should I change it to 'type_map' or the orthers .

**Comment by vqdang** [comment]
Hi, you must download the latest version of the code, which you can see that is different from what you have.

**Comment by simongraham** [comment]
See here:

https://github.com/vqdang/hover_net/blob/master/src/extract_patches.py#L58

In the updated code, we use `type_map` rather than `class_map`

**Comment by haiqinzhong** [comment]
Thank you for your reply , I have download the latest version of the code , and find that . and I'll continue try .

**Comment by haiqinzhong** [comment]
@simongraham @vqdang Thanks for help, I'm training now .  And I'll do others after training . If I have some error,can I ask for your   help again?

**Comment by simongraham** [comment]
No problem. Yes, feel free to reach out, but please open as a new issue.

**Comment by haiqinzhong** [comment]
@simongraham OK.
