### ISSUE TITLE
can't run infer.py well

### ISSUE THREAD

**Issue by haiqinzhong** [vqdang/hover_net#61]
Hi, @simongraham and @vqdang . I can't get anything when I run the infer.py.
![1](https://user-images.githubusercontent.com/56585970/92327535-f97c9300-f08c-11ea-8ed1-e124031bfec7.png)

It can find the best checkpoints.
![2](https://user-images.githubusercontent.com/56585970/92327598-56784900-f08d-11ea-8c67-bb88638389ee.png)

It give the warn : The following variables are in the checkpoint, but not found in the graph: beta1_power:0, beta2_power:0, global_step:0, learning_rate:0 .

So , how can I solve this problem ?

**Comment by vqdang** [comment]
They are variables for training only so missing them have no effect on the inference code.

**Comment by haiqinzhong** [comment]
but I can't get anything in the output folder . so , what should to get the output . Run others flie ? Or the path I change is wrong.
![4](https://user-images.githubusercontent.com/56585970/92423427-ac471100-f1b3-11ea-965d-42eebc6c79f8.png)
I only change the path of  self.save_dir , self.inf_data_dir , self.inf_output_dir .

**Comment by haiqinzhong** [comment]
I think I know what went wrong , this is a stupid mistake that the path of self.inf_data_dir is "test" , but the folder is "Test" , I'll try again , and will let you know if there are new developments .
By the way, can you tell me tell me the purpose of stain_norm.py ? 
 And in this python file , it have the code in line 9 , 10, 20:
imgs_dir = 'data/NUC_UHCW/No_SN/valid/'
save_dir = 'data/NUC_UHCW/SN_5784/valid/'
stain_norm_target = {
    'data/TCGA-21-5784-01Z-00-DX1.tif' : '5784'
}
 Is the NUC_UHCW a dataset ? How can I get it if it is . Also what is the TCGA-21-5784-01Z-00-DX1.tif , how can I get it .

**Comment by haiqinzhong** [comment]
Hi,@vqdang and @simongraham , the infer.py is run fine. And I'm sorry to disturb you again . But I can't find anything to solve the error:
output/v1.0//np_hv/ test_1 Traceback (most recent call last):
  File "process.py", line 97, in <module>
    overlaid_output = visualize_instances(pred_inst, img)
  File "/home/hqzhong/Programs/Hover-net/src/misc/viz_utils.py", line 53, in visualize_instances
    cv2.drawContours(inst_canvas_crop, contours[1], -1, inst_color, 2)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/drawing.cpp:2509: error: (-215:Assertion failed) npoints > 0 in function 'drawContours'
I think the reason for this may be the value of contours[1] is [-1,-1,-1,-1] , but I modify nothing except path .

**Comment by vqdang** [comment]
We don't have any use for `stain_norm.py` in the final version so you don't need to pay attention to it.

>I think the reason for this may be the value of contours[1] is [-1,-1,-1,-1] , but I modify nothing except path .

Opencv 3.2.x has different output protocol compared to 4.x.x , the current viz code is still on 3.2.x . For 4.x.x, just change 
>`cv2.drawContours(inst_canvas_crop, contours[1], -1, inst_color, 2)`

to

>`cv2.drawContours(inst_canvas_crop, contours[0], -1, inst_color, 2)`

**Comment by haiqinzhong** [comment]
@vqdang ，thanks for your help . It run well . But the result seems to be a bit different from your paper . 
![实例分割得分](https://user-images.githubusercontent.com/56585970/92484612-7d18ba00-f21c-11ea-9a43-1f0c645a5cc9.png)
![论文分割得分](https://user-images.githubusercontent.com/56585970/92484622-8144d780-f21c-11ea-8f4e-08571ecfb95b.png)
![分类得分](https://user-images.githubusercontent.com/56585970/92484634-86a22200-f21c-11ea-90f2-9d6d54549688.png)
![论文分类得分](https://user-images.githubusercontent.com/56585970/92484655-8bff6c80-f21c-11ea-9066-9b1accc02b18.png)
as you can see . the 1st is my score of instance and 2nd is your paper's . the same , 3rd is my score of type and 4th is your paper's .
with the score order in your code . my instace score is 
0.850 , 0.546(the aji_plus is 0.570) , 0.674 , 0.768 , 0.519    
which same order as your score in paper . so , my type score is
0.519(PQ score from instance) , 0.738 , 0.646 , 0.565 , 0.537 , 0.357
by the way , in the whole process，I only use your dataset CoNSep ,training set and test set for train and infer respectively .
Why?

**Comment by simongraham** [comment]
Your scores do not seem too different to our reported results. We use the maximum dice score to select the 'optimal' checkpoint, but this may not in fact give us the best instance segmentation performance. You should select a different checkpoint and see the effect on the results. We also use this strategy for selecting the checkpoint when also performing classification. Ideally we should use a better criterion for checkpoint selection.

**Comment by haiqinzhong** [comment]
OK , I'll try again . thank you for your reply.

**Comment by haiqinzhong** [comment]
Hi, @simongraham and @vqdang .I'm sorry to bother you again . First, thanks for help me solve the errors.  But when I train other  models in your code ,they have some errors .
**When I use "model=hover  model_type=np_dist " and "model=other  model_type=dcan " to train, it tell me :** 
Traceback (most recent call last):
  File "train.py", line 271, in <module>
    trainer.run()
  File "train.py", line 251, in run
    self.run_once(opt, sess_init=init_weights, save_dir=self.save_dir)
  File "train.py", line 211, in run_once
    launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(nr_gpus))
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/train/interface.py", line 97, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/train/base.py", line 341, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/train/base.py", line 313, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/train/base.py", line 285, in main_loop
    self._callbacks.trigger_epoch()
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 149, in trigger_epoch
[0911 20:48:47 @input_source.py:174] EnqueueThread QueueInput/input_queue Exited.
    self._trigger_epoch()
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 97, in _trigger_epoch
    cb.trigger_epoch()
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 149, in trigger_epoch
    self._trigger_epoch()
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 155, in _trigger_epoch
    self.trigger()
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 158, in trigger
    self._trigger()
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/callbacks/inference_runner.py", line 312, in _trigger
    inf.trigger_epoch()
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 149, in trigger_epoch
    self._trigger_epoch()
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/callbacks/inference.py", line 43, in _trigger_epoch
    ret = self._after_inference()
  File "train.py", line 92, in _after_inference
    pred_np = pred_inst[...,0]
IndexError: index 0 is out of bounds for axis 3 with size 0
[0911 20:48:47 @input_source.py:174] EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue Exited.

**And when I use "model=hover  model_type=np_dist " and "model=other  model_type=dcan " to train, it tell me :** 
[0911 20:46:10 @input_source.py:168] ERR Exception in EnqueueThread QueueInput/input_queue:
Traceback (most recent call last):
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 161, in run
    self.op.run(feed_dict=feed)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2368, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5192, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (8, 256, 256, 2) for Tensor 'truemap-coded:0', which has shape '(?, 256, 256, 1)'
[0911 20:46:10 @input_source.py:174] EnqueueThread QueueInput/input_queue Exited.
[0911 20:46:11 @concurrency.py:37] Starting EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue ...
[0911 20:46:11 @inference_runner.py:101] [InferenceRunner] Will eval 14 iterations
[0911 20:46:11 @base.py:272] Start Epoch 1 ...
  0%|                                                                                                                                                                                         |0/54[00:00<?,?it/s][0911 20:46:11 @input_source.py:168] ERR Exception in EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue:
Traceback (most recent call last):
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 161, in run
    self.op.run(feed_dict=feed)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2368, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5192, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (16, 256, 256, 2) for Tensor 'truemap-coded:0', which has shape '(?, 256, 256, 1)'
[0911 20:46:12 @input_source.py:174] EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue Exited.
[0911 20:46:12 @base.py:288] Training was stopped by exception FIFOQueue '_0_QueueInput/input_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[node QueueInput/input_deque (defined at /home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/input_source/input_source.py:267)  = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](QueueInput/input_queue)]]

Caused by op 'QueueInput/input_deque', defined at:
  File "train.py", line 271, in <module>
    trainer.run()
  File "train.py", line 251, in run
    self.run_once(opt, sess_init=init_weights, save_dir=self.save_dir)
  File "train.py", line 211, in run_once
    launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(nr_gpus))
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/train/interface.py", line 87, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/train/tower.py", line 204, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/train/trainers.py", line 106, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 161, in build
    grad_list = DataParallelBuilder.build_on_towers(self.towers, get_grad_fn, devices)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 119, in build_on_towers
    ret.append(func())
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/train/tower.py", line 232, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/input_source/input_source_base.py", line 82, in get_input_tensors
    return self._get_input_tensors()
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 267, in _get_input_tensors
    ret = self.queue.dequeue(name='input_deque')
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 435, in dequeue
    self._queue_ref, self._dtypes, name=name)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3741, in queue_dequeue_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_0_QueueInput/input_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[node QueueInput/input_deque (defined at /home/hqzhong/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/input_source/input_source.py:267)  = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](QueueInput/input_queue)]]


Can you teach me what are these errrors and how to solove?
Thank you for help me a lot again.

**Comment by vqdang** [comment]
Please edit your message so it looks readable, seems you duplicated 2 times.
Anyways, these variables are for other model available. 
https://github.com/vqdang/hover_net/blob/5d1560315a3de8e7d4c8122b97b1fe9b9513910b/src/config.py#L20 for network definition
https://github.com/vqdang/hover_net/blob/5d1560315a3de8e7d4c8122b97b1fe9b9513910b/src/config.py#L21 for GT definition
`model='dcan'` and `self.model_type='dcan'` should lets it runs the training on DCAN.

Make another issue for this as this question doesnt relate to this issue.

**Comment by Ghulam111** [comment]
@haiqinzhong what are the images you have picked for the validation set. have you changed the test set or is it the same ? please mention the names of images you have selected for validation set.i want to have exact same split of images as you have.
