### ISSUE TITLE
Im running the tensorflow version of your code, while i try to train dcan model i get this below error.

### ISSUE THREAD

**Issue by Thejas05** [vqdang/hover_net#84]
**libcublas.so.9.0: cannot open shared object file: No such file or directory**
Im running tf 1.12

**Comment by vqdang** [comment]
You need to use correct cuda version for each version of the tensorflow / pytorch.

**Comment by Thejas05** [comment]
Hello thankyou for the reply i changed my cuda toolkit to 9.0, but now im having a different error!

 **E:\NITK\DCAN\hover_net-tensorflow-final\src>python train.py --gpu='0'
[256, 256] [256, 256]
Traceback (most recent call last):
  File "train.py", line 272, in <module>
    trainer.run()
  File "train.py", line 252, in run
    self.run_once(opt, sess_init=init_weights, save_dir=self.save_dir)
  File "train.py", line 174, in run_once
    train_datagen = self.get_datagen(opt['train_batch_size'], mode='train')
  File "train.py", line 162, in get_datagen
    nr_procs=nr_procs)
  File "E:\NITK\DCAN\hover_net-tensorflow-final\src\loader\loader.py", line 73, in train_generator
    ds = PrefetchDataZMQ(ds, nr_procs)
  File "E:\Anaconda Nav\envs\hovernet_tf\lib\site-packages\tensorpack\dataflow\parallel.py", line 285, in __init__
    super(PrefetchDataZMQ, self).__init__()
  File "E:\Anaconda Nav\envs\hovernet_tf\lib\site-packages\tensorpack\dataflow\parallel.py", line 91, in __init__
    assert os.name != 'nt', "ZMQ IPC doesn't support windows!"
AssertionError: ZMQ IPC doesn't support windows!**

**Comment by Thejas05** [comment]
Okay i got it thankyou! had to comment the line in loader.py
