### ISSUE TITLE
Hello again! i was trying to run dcan model, it keeps giving me false for cpu

### ISSUE THREAD

**Issue by Thejas05** [vqdang/hover_net#85]
(hovernet_tf) E:\NITK\DCAN\hover_net-tensorflow-final\src>python train.py --gpu='0'
[256, 256] [256, 256]
[256, 256] [256, 256]
[32m[0113 11:12:06 @logger.py:108][0m [5m[31mWRN[0m Log directory E:\NITK\DCAN\hover_net-tensorflow-final\src\/v1.0//dcan exists! Use 'd' to delete it.
[32m[0113 11:12:06 @logger.py:111][0m [5m[31mWRN[0m If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit.
Select Action: k (keep) / d (delete) / q (quit):d
[32m[0113 11:12:08 @logger.py:73][0m Argv: train.py --gpu='0'
2021-01-13 11:12:08.511845: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "train.py", line 272, in <module>
    trainer.run()
  File "train.py", line 252, in run
    self.run_once(opt, sess_init=init_weights, save_dir=self.save_dir)
  File "train.py", line 185, in run_once
    model = self.get_model()(**model_flags)
  File "E:\NITK\DCAN\hover_net-tensorflow-final\src\model\dcan.py", line 19, in __init__
    assert tf.test.is_gpu_available()
AssertionError

**Comment by simongraham** [comment]
Hi. First of all, can you please provide more info. Are you using the library versions that we specify? Please provide the tensorflow and tensorpack versions. Also please confirm that you can see installed GPUs with ‘nvidia-simi’ if using Linux.

**Comment by Thejas05** [comment]
Thankyou for the reply , actually I came to know what the problem is, my GPU doesn't support cuda 9.0 is there any solution for this. Or what are the chances I have to do to shift to 1.15 tf

**Comment by Thejas05** [comment]
i checked if my gpu is getting detected, it is getting detected, but when i run the train.py file its not getting detected, i get the same error as before. Below shows the detected gpu.

>>> import tensorflow as tf
>>> assert tf.test.is_gpu_available()
2021-01-14 10:35:40.401139: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-01-14 10:35:40.898864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2021-01-14 10:35:40.906038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2021-01-14 10:35:41.644642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-14 10:35:41.648540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2021-01-14 10:35:41.650365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2021-01-14 10:35:41.652367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 3017 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)

**Comment by simongraham** [comment]
The tensorflow version of this code does not support version 1.15. You must use the specified library versions otherwise you will run into issues like what you are seeing above. 

An alternative would be to add DCAN as a model within the PyTorch version of the code. HoVer-Net is contained within its own folder [here](https://github.com/vqdang/hover_net/tree/pytorch/models/hovernet). In the same way, you can add a DCAN folder and appropriately port over the code. 

However, the quickest way would be to ensure that the **correct libraries** are used using the TF code.

**Comment by Thejas05** [comment]
Hi! i just wanted to know if the code supports single GPU or is it modifiable for a single GPU.

**Comment by vqdang** [comment]
@Thejas05 The current pytorch codes can use any gpu exposed to the script via setting the `CUDA_VISIBLE_DEVICES` environment variables. The tensorflow code doesnt support multiple gpu for inference, but for training script the gpus usage is similar to pytorch.

**Comment by Thejas05** [comment]
@vqdang actually I wanted to know if the tensorflow code works with a single GPU, because I don't have a multiple GPU Setup

**Comment by vqdang** [comment]
@Thejas05 It supports single gpu, you just need to suppy `--gpu 0` accordingly.

**Comment by simongraham** [comment]
Closing this issue as the conversation is now off topic to the title of the issue. Please open up a new issue if you have further questions.
