### ISSUE TITLE
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [1, 1, 5, 5], but got 3-dimensional input of size [80, 1, 80] instead

### ISSUE THREAD

**Issue by michalstepniewski** [vqdang/hover_net#94]
Traceback (most recent call last):
  File "run_train.py", line 300, in <module>
    trainer.run()
  File "run_train.py", line 280, in run
    phase_info, engine_opt, save_path, prev_log_dir=prev_save_path
  File "run_train.py", line 256, in run_once
    main_runner.run(opt["nr_epochs"])
  File "/data/Praca/TTMS/hover_net/run_utils/engine.py", line 182, in run
    step_output = self.run_step(data_batch, step_run_info)
  File "/data/Praca/TTMS/hover_net/models/hovernet/run_desc.py", line 75, in train_step
    term_loss = loss_func(*loss_args)
  File "/data/Praca/TTMS/hover_net/models/hovernet/utils.py", line 166, in msge_loss
    true_grad = get_gradient_hv(true)
  File "/data/Praca/TTMS/hover_net/models/hovernet/utils.py", line 158, in get_gradient_hv
    h_dh_ch = F.conv2d(h_ch, kernel_h, padding=2)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [1, 1, 5, 5], but got 3-dimensional input of size [80, 1, 80] instead
Processing: |                       | 0/1323[00:00<?,?it/s]Batch = nan|EMA = nan

**Comment by vqdang** [comment]
Hi, did you provide batch_size=1 ?

**Comment by michalstepniewski** [comment]
yeah, was going to close it. 

Now I am having problem with inference though ... 

python run_infer.py tile --nr_types=5 --model_path='../pretrained/ImageNet-ResNet50-Preact_pytorch.tar' --input_dir='dataset/CoNSeP/Train/Images' --output_dir='.'
usage:
    tile (--input_dir=<path>) (--output_dir=<path>)          [--draw_dot] [--save_qupath] [--save_raw_map]

**Comment by vqdang** [comment]
There is `run_tile.sh` and `run_wsi.sh` to show you how to use the cmd. Anyways close the issue due to not related.
